spring:
  application:
    name: backend-course
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-course
    username: ct250
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
